### ISSUE TITLE
how to compute epicentral distance 

### ISSUE THREAD

**Issue by seismoprocess** [paudetseis/PyRaysum#2]
Hii, paudetseis is it possible to obtain epicentral distance using this software, i obtain only back azimuth and slowness information along with time, r,t,z values. Or can the back-azimuth be assumed as epicentral distance in the case of raysum. Please suggest.Thanks.

**Comment by wsja** [comment]
To relate backazimuth, ray slowness and distance, use: [obspy.taup.tau.TauPyModel](https://docs.obspy.org/packages/autogen/obspy.taup.tau.TauPyModel.html#obspy-taup-tau-taupymodel)
