### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by rafa0110** [paudetseis/PyRaysum#22]
Hi! 
I just have two question. How to change the position of the sensor in the program? 
1. In the attached picture it is at 0 km. Would it be possible to change to order coordinate? For example -60?
2. In this Class --- >pyraysum.prs.Geometry(baz, slow, dn=0, de=0, maxtr=500). We have dn and de. What does it mean exactly dn and de? the North and East epicentral distance from source to receiver?

![question](https://github.com/paudetseis/PyRaysum/assets/70123899/44361079-2e56-4636-9226-b395122f3326)

Thanks for this amazing package!

**Comment by paudetseis** [comment]
Hi!

The answer is here: https://paudetseis.github.io/PyRaysum/api.html#pyraysum.prs.Geometry

`dn` and `de` are offset positions of a seismic station relative to a position at `0`. These can be used to simulate waveforms for an array of stations (although one at a time).
